services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: srm_hypertrophy_app_db
      POSTGRES_USER: srm_hypertrophy_app_user
      POSTGRES_PASSWORD: srm_hypertrophy_app_pw
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
